import type { Metadata } from 'next';
import ThemeRedux from '@/lib/ThemeRedux';
import './globals.css';
import { QueryProvider } from './QueryProvider';
import { ConfigProvider } from 'antd';
import AuthProvider from './AuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" suppressHydrationWarning={true}>
      <body>
        <AuthProvider>
          <QueryProvider>
            <ThemeRedux>
              <ConfigProvider theme={{ cssVar: true }}>
                {children}
              </ConfigProvider>
            </ThemeRedux>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
