export const env = {
  API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT,
  API_ROOT_PHOTO: process.env.NEXT_PUBLIC_API_ROOT_PHOTO,
  URL_IMG_DEFAULT: process.env.NEXT_PUBLIC_URL_IMG_DEFAULT,

  TOKEN_EXPIRE_NUMBER: process.env.TOKEN_EXPIRE_NUMBER,
  TOKEN_EXPIRE_UNIT: process.env.TOKEN_EXPIRE_UNIT,

  NEXT_AUTH_SECRET: process.env.NEXT_AUTH_SECRET,
};
