import type { Metadata } from 'next';
import Header from './_components/header';
import Footer from './_components/footer';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      <section>{children}</section>
      <Footer />
    </div>
  );
}
